### ISSUE TITLE
界面字体问题

### ISSUE THREAD

**Issue by tojo17** [Javran/poi-plugin-leveling#1]
中文和日文汉字的字体是宋体，可以说是非常丑了，希望改进，多谢！
![image](https://user-images.githubusercontent.com/5460009/27848612-0ea88be0-6179-11e7-82d0-0f197049bf41.png)

**Comment by KochiyaOcean** [comment]
~~~当代 Windows 还不预装 Ubuntu 和 Source Hans Sans 可以说是不太行了~~~

**Comment by tojo17** [comment]
~~然而我装的是 Noto Sans CJK qwq~~
~~另外系统是英文系统，不是很理解为啥会 fallback 到宋体~~

**Comment by Javran** [comment]
应该已经修好了,新版本1.1.0. 这个issue先关了,若有问题欢迎进一步反馈.
